services:
  web:
    image: ghcr.io/studi-bars/studi-bars/django-app:main
    build:
      context: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/uploads
    expose:
      - 8000
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: studi-bars
      SQL_USER: django
      SQL_PASSWORD: studi-bars
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: studi-bars
      POSTGRES_DB: studi-bars
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: ghcr.io/studi-bars/studi-bars/nginx:main
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/uploads
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: