# Generated by Django 5.0.3 on 2024-06-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='location',
        ),
        migrations.AddField(
            model_name='bar',
            name='city',
            field=models.CharField(default='Aachen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='menu_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='street',
            field=models.CharField(default='', help_text='Straße und Hausnummer', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='zip_code',
            field=models.CharField(default='52072', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='open',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, '1./3./5.')], default=1, help_text='Sowas wie jede Woche, 1./3./5. Mittwoch'),
        ),
    ]
