# Generated by Django 5.0.3 on 2024-06-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bar_location_bar_city_bar_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
