# Generated by Django 5.0.3 on 2024-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bar_latitude_alter_bar_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='tags',
            field=models.CharField(default='', help_text='Komma separierte Liste an Tags', max_length=254),
        ),
    ]
