# Generated by Django 5.0.3 on 2024-06-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bar_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='open',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, '1. 3. 5.')], default=1, help_text='Sowas wie jede Woche, 1./3./5. Mittwoch'),
        ),
        migrations.CreateModel(
            name='BarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bar_images/')),
                ('order', models.IntegerField(default=0, help_text='Displayed from highest to lowest. If number, from oldest to newest')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.bar')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
