# Generated by Django 5.0.3 on 2024-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bar_created_at_bar_updated_at_barimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Komma separierte Liste an Tags', max_length=254),
        ),
    ]
