# Generated by Django 5.0.6 on 2024-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bar_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
