# Generated by Django 5.0.6 on 2024-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bar_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook Gruppe/Seite', null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Whatsapp Gruppe/Newsletter etc', null=True),
        ),
    ]
