# Generated by Django 5.0.6 on 2024-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bar_facebook_bar_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='temporarily_closed',
            field=models.BooleanField(default=False),
        ),
    ]
