# Generated by Django 5.0.6 on 2025-03-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bar_temporarily_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Should this event be excluded from Google Search'),
        ),
    ]
