# Generated by Django 5.0.6 on 2025-03-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_no_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Exclude this event from the google search index'),
        ),
    ]
