# Generated by Django 5.0.6 on 2025-06-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_event_no_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('ingredients', models.CharField(blank=True, max_length=512, null=True)),
                ('note', models.CharField(blank=True, help_text='z.B. "ab 22 Uhr", "von 23 bis 01 Uhr", "bis Mitternacht"', max_length=20, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_drinks', to='main.event')),
            ],
        ),
    ]
