# Generated by Django 5.2.12 on 2026-05-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_specialdrink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Removes the Date from the URL. You have to update the date at every recurrence.'),
        ),
    ]
